### ISSUE TITLE
visitor visits home page

### ISSUE THREAD

**Issue by Jpease1020** [Jpease1020/ez_eats#1]

**Comment by Jpease1020** [comment]
Just a beginning

**Comment by Jpease1020** [comment]
As a visitor, when I visit the home page (root path),  I can see section with a link to the blogs, the reviews and the food challenges and I should see the carousel of pictures on the page.  I can also see the nav-bar with links to the other pages including the option for logging in or creating an account.

**Comment by mbburch** [comment]
finished except for broken carousel functionality.
